### ISSUE TITLE
About the ability of these riscv litmus tests in helping detect and repair of bugs in riscv implementation

### ISSUE THREAD

**Issue by DehengYang** [litmus-tests/litmus-tests-riscv#10]
Dear Authors,

Sorry for interrupting you with this question. I am very interested in this work that automatically generates a large number of litmus tests for riscv. This significantly saves huge manual effort and makes the memory model testing more robust. Meanwhile, a question naturally arises in my mind: **Have the litmus tests generated for riscv ever helped the detection or repair of any bugs in RISC-V implementation?**

It would be much appreciated if any guidance could be provided. Thank you!

Yours sincerely,
Deheng

**Comment by PeterSewell** [comment]
On Fri, 21 Apr 2023 at 04:42, Deheng Yang ***@***.***> wrote:

> Dear Authors,
>
> Sorry for interrupting you with this question. I am very interested in
> this work that automatically generates a large number of litmus tests for
> riscv. This significantly saves huge manual effort and makes the memory
> model testing more robust. Meanwhile, a question naturally arises in my
> mind: *Have the litmus tests generated for riscv ever helped the
> detection or repair of any bugs in RISC-V implementation?*
>
Not to my knowledge, however
- if a vendor that we weren't working closely with had discovered bugs
using them, they probably wouldn't tell us;
- early RISC-V implementations (including those that we know tests were run
on) were not very aggressively out-of-order, so less likely to have such
bugs; and
- analogous tests for other architectures have discovered a number of bugs
in a number of processor implementations.

best,
Peter

**Comment by DehengYang** [comment]
Thank you very much for the prompt guidance!

> - if a vendor that we weren't working closely with had discovered bugs
using them, they probably wouldn't tell us;

Get it. This is really understandable. 

> - analogous tests for other architectures have discovered a number of bugs in a number of processor implementations.

Thank you very much for providing this clue! These days I have been always feeling confused about how many benefits the memory model simulation and testing tool could bring to the community. I have read several papers, e.g.,

1) Fences in Weak Memory Models: *This work identified a rare implementation error in Power 5 memory barriers (for which IBM is providing a workaround);*
2) Partial Orders for Efficient Bounded Model Checking of Concurrent Software: *We confirm a bug in the worker synchronisation mechanism in PostgreSQL, and that adding two fences fixes the problem.*

...

But such cases are seemingly rare, which perhaps makes it hard to understand its industrial impact.

Thank you again for the guidance and wish you a nice day!

Yours,
Deheng

**Comment by PeterSewell** [comment]
On Fri, 21 Apr 2023 at 07:56, Deheng Yang ***@***.***> wrote:

> Thank you very much for the prompt guidance!
>
>
>    - if a vendor that we weren't working closely with had discovered bugs
>    using them, they probably wouldn't tell us;
>
> Get it. This is really understandable.
>
>
>    - analogous tests for other architectures have discovered a number of
>    bugs in a number of processor implementations.
>
> Thank you very much for providing this clue! These days I have been always
> feeling confused about how many benefits the memory model simulation and
> testing tool could bring to the community. I have read several papers, e.g.,
>
>    1. Fences in Weak Memory Models: *This work identified a rare
>    implementation error in Power 5 memory barriers (for which IBM is providing
>    a workaround);*
>    2. Partial Orders for Efficient Bounded Model Checking of Concurrent
>    Software: *We confirm a bug in the worker synchronisation mechanism in
>    PostgreSQL, and that adding two fences fixes the problem.*
>
> ...
>
> But such cases are seemingly rare, which perhaps makes it hard to
> understand its industrial impact.
>
One benefit is in the finding of subtle bugs, but the larger benefit is on
clarifying what the intended models are - before such work, for many
mainstream architectures and languages, that was quite unclear.  Some
vendors (e.g. Arm) now have substantial groups working on this internally,
there are other papers that point out and fix flaws in compilation schemes,
from languages to hardware, and there's also a lot of work on GPU
concurrency.

Peter

**Comment by DehengYang** [comment]
Dear Prof. Sewell,

Thank you so much for the detailed guidance. That perfectly solves my doubt. Thanks again for the great work which has offered the area of memory consistency model a formal modeling approach and an adequate testing solution. Much appreciated.

Yours,
Deheng
