### ISSUE TITLE
which model do the simulation results for?

### ISSUE THREAD

**Issue by N1neSun** [litmus-tests/litmus-tests-riscv#14]
![7e252b61ccab9b39efc5d93a8b3770f](https://github.com/litmus-tests/litmus-tests-riscv/assets/13716571/b589ae2d-880b-4ed4-95d6-5ebfa8be5d69)
Hi,Would like to ask are these test results in flat.log and herd.log based on the RVWMO or RVTSO? Further, which .cat file you used to test by herd7, riscv.cat or riscv-tso.cat?

**Comment by fshaked** [comment]
Hi N1neSun,

The model logs are based on RVWMO (you can see in the logs that the LB test is exhibited, so it cannot be TSO). The herd.log file was generated using riscv.cat (you can see that in the Makefile).

Best,
Shaked

**Comment by N1neSun** [comment]
Thank you very much for your answer and I wish you a Merry Weekend and Christmas in advance.

**Comment by N1neSun** [comment]
Hi fshaked,

Could you please illustrate the meaning of condition in .litmus file(for example, " exists (1:x5=1 /\ 1:x7=0)   " and " for all (1:x5=1 /\ 1:x7=0)  ") and how to analyze the test results.     

In my opinion, it demenstrate there is something OoO(out of order) happened in program order if any witness for  "exists (1:x5=1 /\ 1:x7=0) " and I have to clear whether the memory model of my hardware allowing this OoO behaviour.     

Moreover，could I consider the model results by herd7 as the golden results?  In other words, if I see "!!!Warning negative differences in: [...    ]" when I compare the results ran by hardware which is applied RVWMO with the model results, I should doubt whether the hardware in violation of RVWMO.

I am confused about whether my understanding is correct and I am looking forward to your reply.btw,I wish you a Merry Christmas

BR,
N1neSun

**Comment by fshaked** [comment]
Hi N1neSun,

The exists/forall condition is usually added by the diy tool that we use to generate the tests. It should be seen as a comment, and in most use cases you should just ignore it. The condition indicates the execution that motivated the generation of the test, but it doesn't say anything about the intended model. You can read more about [diy7 here](https://diy.inria.fr/doc/gen.html#part%3Adiy).

Yes, if you see "negative differences" from mcompare, when comparing to the herd (or Flat) model (assuming you run it as in the Makfile; note that the order of the input files is very important), the hardware violates RVWMO. As far as I know, for non-mixed-size application code, the herd, Flat, and the description of RVWMO in the RISC-V manual are all the same. mcompare ignores the exists/forall condition, it compares the exhibited final states, and this is what you care about if you're trying to validate some hardware (or another model?). What are you actually trying to achieve, if you don't mind sharing details?

Best,
Shaked

**Comment by N1neSun** [comment]
Hi Shaked，

Thank you very much for your answers！

Yes，as you guessed，my purpose is to validate some RISCV hardware by this test set and also compare the results of them. I saw the litmus test in the RISCV manual and tried to test it recently. However，maybe the hardware is not exactly match with RVWMO(it is supposed  to be weaker), so I need to kown more about the principles of the litmus that is favorable to analyze and evaluate my validation results. 

There are still many details I am not clear about litmus test protype, such as the syntax description of the cycle, how to set safe and relax, etc… Could you please list some fundamental learning materials or papers about the litmus test and memory model theories if it doesn‘t bother you?

Thanks again for your kindness and help.😊

BR，
N1neSun

**Comment by fshaked** [comment]
There's a lot of work on memory models on [Peter's page](https://www.cl.cam.ac.uk/~pes20/papers/topics.html#relaxed_all). Maybe start from the [tutorial](https://www.cl.cam.ac.uk/~pes20/ppc-supplemental/test7.pdf). The [Simplifying ARM paper](https://www.cl.cam.ac.uk/~pes20/armv8-mca/armv8-mca-draft.pdf) describes the Arm Flat model which is very similar to the RISC-V model. There's also [Christopher's thesis](https://www.repository.cam.ac.uk/items/27183ea1-7ed2-40f4-8a21-442c576d888a). You can use the [rmem tool web-interface](http://www.cl.cam.ac.uk/users/pes20/rmem) to explore the operational memory models and litmus tests.

The best place to read about litmus test syntax and how to generate tests is probably the [documentation of diy](https://diy.inria.fr/doc/index.html). Luc Maranget maintains the [github repo](https://github.com/herd/herdtools7). A lot of this, and axiomatic models, are also documented in Alglave et al. paper [Herding cats](https://diy.inria.fr/herd/herding-cats-bw.pdf).

**Comment by PeterSewell** [comment]
On Wed, 27 Dec 2023 at 09:19, Shaked Flur ***@***.***> wrote:

> There's a lot of work on memory models on Peter's page
> <https://www.cl.cam.ac.uk/~pes20/papers/topics.html#relaxed_all>. Maybe
> start from the tutorial
> <https://www.cl.cam.ac.uk/~pes20/ppc-supplemental/test7.pdf>.
>
Perhaps better start from, or supplement that with, our Multicore slides,
https://www.cl.cam.ac.uk/~pes20/slides-acs-2022.pdf

**Comment by N1neSun** [comment]
Thank you very much for your response and the valuable resources you provided. I will diligently study the materials, especially those related to the RVWMO memory model and the documentation of the diy tool. Your guidance is greatly appreciated.
