### ISSUE TITLE
Identifying Unconventional Assembly Instructions in RISC-V Context: The Case of lw.aq in Litmus Tests

### ISSUE THREAD

**Issue by GTwhy** [litmus-tests/litmus-tests-riscv#15]
Hi, I found some assembly instructions that are not in the RISC-V instruction set and am unsure of their meaning. For example: `lw.aq x5,0(x6)` at [this link](https://github.com/litmus-tests/litmus-tests-riscv/blob/1fe2afdcc121566fda2c97d324c26c58a33ea56d/tests/non-mixed-size/SAFE/LB%2Bpoaqps.litmus#L15).

To my knowledge, RISC-V does not currently have plain load and store opcodes with aq or rl annotations.

**Comment by GTwhy** [comment]
I saw this [discussion](https://github.com/litmus-tests/litmus-tests-riscv/issues/1#issuecomment-451391470), so it seems that some tests merely assume that loads and stores support the aqrl encoding for testing purposes, and they cannot actually be compiled and run at the moment, correct?

**Comment by pdonahue-ventana** [comment]
They're part of the Zalasr extension which is not yet ratified but which is a [fast-track](https://lists.riscv.org/g/tech-unprivileged/message/580) extension.

See https://github.com/mehnadnerd/riscv-zalasr

**Comment by GTwhy** [comment]
Understood, thanks for your reply! @pdonahue-ventana
