### ISSUE TITLE
C-Will02+HEAD failed on spike64

### ISSUE THREAD

**Issue by zetalog** [litmus-tests/litmus-tests-riscv#2]
I ran all compiled gcc (8.1.0, released by kernel.org) cases on spike64, and failed only 1 case, the witnessed result looks possible to me if P1 executes after P0 completes execution of all instructions.

```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Results for tests/non-mixed-size/HAND/C-Will02+HEAD.litmus %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
RISCV C-Will02+HEAD
{ok=1; 0:x6=x; 0:x7=y; 0:x3=z; 1:x6=y; 1:x8=x; 1:x3=z;}
 P0                     | P1          ;
 ori x5,x0,1            | ori x1,x0,1 ; 
 sw x5,0(x6)            | sw x1,0(x3) ;
 ori x8,x0,1            | fence rw,rw ;
 fence rw,rw            | lw x7,0(x6) ;
 amoadd.w.aq x9,x5,(x7) |             ;
 lw x2,0(x3)            |             ;

locations [0:x2;]
exists (0:x9=0 /\ 1:x7=0)
Generated assembler
Test C-Will02+HEAD Allowed
Histogram (2 states)
6     *>0:x2=1; 0:x9=0; 1:x7=0;
4     :>0:x2=0; 0:x9=0; 1:x7=1;
Ok

Witnesses
Positive: 6, Negative: 4
Condition exists (0:x9=0 /\ 1:x7=0) is validated
Hash=2e871110536e293e85fd831b51b2c42f
Observation C-Will02+HEAD Sometimes 6 4
Time C-Will02+HEAD 0.00
```

So my question is: is the case itself wrong or something missing in the case source file?

**Comment by fshaked** [comment]
Looking in model-results/flat.logs I see for this test the following states:
0:x2=0x0; 0:x9=0x0; 1:x7=0x1; 
0:x2=0x1; 0:x9=0x0; 1:x7=0x0; 
0:x2=0x1; 0:x9=0x0; 1:x7=0x1; 
(and the same in herd.logs)

Those are all the states the model allows. spike64 exhibited just two of those. This is expected, as simulators usually are more restricted than the architecture (i.e. model).

The "Negative: 4" just means that some of the states spike exhibited don't satisfy the assertion in the test, but this assertion is not very meaningful (it highlights an interesting behaviour, it doesn't mean other states are forbidden). The important thing is that all the states spike exhibited are allowed by the model.

**Comment by zetalog** [comment]
> Those are all the states the model allows.
I agreed.

> The "Negative: 4" just means that some of the states spike exhibited don't satisfy the assertion in the test, but this assertion is not very meaningful (it highlights an interesting behaviour, it doesn't mean other states are forbidden).
Disagreed, as we can add "filter" to make it meaningful like what tests/non-mixed-size/HAND/ISA03+SB01 and some other cases do.

**Comment by fshaked** [comment]
I'm not sure I understand what you mean. Maybe in ISA03+SB01 the assertion
indicates the only valid state, but this is not the case in general. To
check if hw/simulator observations conform to the model you need to check,
using mcompare7, if all the states exhibited by the hw are also exhibited
by the model. The assertion is usually not a reliable indication.

**Comment by zetalog** [comment]
> Maybe in ISA03+SB01 the assertion indicates the only valid state, but this is not the case in general. 

OK. If you think nothing to be improved in the case, let me close the issue.
