### ISSUE TITLE
Luc02+BIS.litmus question

### ISSUE THREAD

**Issue by hillelme** [litmus-tests/litmus-tests-riscv#5]
@fshaked 
Hi,
I'm looking at https://github.com/litmus-tests/litmus-tests-riscv/blob/master/tests/non-mixed-size/HAND/Luc02%2BBIS.litmus
if the execution order is something like:
```
p1: x5 =  *y       = 0
p1: store 1 in *x
p0: store 2 in *x
p0: store 1 in *y
p1: x9 =  *x       = 2
```
wouldn't we get all the conditions for the fail?
Thank you

**Comment by fshaked** [comment]
Hi @hillelme,
The condition at the bottom of the litmus test doesn't necessarily indicate a failure. It mostly highlights an interesting final state. To see if this state is valid, you need to check if the models allow it. You can find model results [here](https://github.com/litmus-tests/litmus-tests-riscv/tree/master/model-results), or you can run the models yourself. The results for Luc02+BIS, from the Flat operational model, are below. The Flat operational model allows 4 final states, which include the highlighted state (I added a comment below to point it out).

```
#Revision: 5120 (not clean)
#Command line: rmem -model flat -interactive false -pp_hex true -q -shallow_embedding true -eager true -hash_prune true tests/non-mixed-size/HAND/Luc02+BIS.litmus
#Model: [flat; not-restricted; flowing_same_address_strict; forbid_uncommitted_read; restart_on_read_satisfy; allow_tree_speculation; forbid_write_subsumption; allow_loops; promising_stop_certifying_after_stop_promising; promising_total_order; use_old_coherence; propagate_at_end; promise_anytime]
#Endianness: little endian
Test Luc02+BIS Allowed
States 4
1:x5=0x0; 1:x9=0x1; x=0x1; 
1:x5=0x0; 1:x9=0x1; x=0x2; 
1:x5=0x0; 1:x9=0x2; x=0x2;  <<< THE HIGHLIGHTED STATE
1:x5=0x1; 1:x9=0x1; x=0x1; 
Ok
Condition exists (1:x5=0x0 /\ 1:x9=0x2 /\ x=0x2)
Hash=9cafd343ff265b5f9f63a498abf38571
Observation Luc02+BIS Sometimes 1 3
Runtime: 0.251230 sec
```
